/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.dmi3y.behaiv;

import de.dmi3y.behaiv.kernel.KernelTest;
import de.dmi3y.behaiv.kernel.LogisticRegressionKernel;
import de.dmi3y.behaiv.provider.TestProvider;
import io.reactivex.rxjava3.core.Observable;
import org.apache.commons.math3.util.Pair;
import org.junit.Before;
import org.junit.Test;

import java.util.ArrayList;

import static de.dmi3y.behaiv.kernel.KernelTest.WORK;
import static org.junit.Assert.assertEquals;

public class LibraryTest {
    Behaiv behaiv;
    private TestProvider positionProvider;
    private TestProvider timeProvider;
    private ArrayList<Pair<ArrayList<Double>, String>> data;

    public static final String WORK_SCREEN = "WORK_SCREEN";

    @Before
    public void setUp() throws Exception {
        behaiv = Behaiv.with("testid");
        behaiv.setKernel(new LogisticRegressionKernel());
        positionProvider = new TestProvider(new String[]{"latitude", "longitude"}, new Double[]{10.10, 10.10});
        timeProvider = new TestProvider(new String[]{"time"}, new Double[]{9.0 * 60 + 30.0});
        behaiv.setProvider(positionProvider);
        behaiv.setProvider(timeProvider);
        data = KernelTest.getTrainingData();
    }

    @Test
    public void behaivTest_basicTestFlow_predictsJob() throws Exception {
        for (Pair<ArrayList<Double>, String> fToL : data) {
            ArrayList<Double> features = fToL.getFirst();
            timeProvider.next(new Double[]{features.get(0)});
            positionProvider.next(new Double[]{features.get(1), features.get(2)});
            capture(fToL.getSecond());
        }

        Observable<String> register = behaiv.subscribe();
        timeProvider.next(new Double[]{(11 * 60 + 30.0) / (24 * 60)});
        positionProvider.next(new Double[]{WORK[0], WORK[1]});
        behaiv.startCapturing(true);
        String predictionResult = register.blockingFirst();
        assertEquals(WORK_SCREEN, predictionResult);

    }

    public void capture(String screenName) throws InterruptedException {
        behaiv.startCapturing(false);
        Thread.sleep(100);
        behaiv.registerLabel(screenName);
        behaiv.stopCapturing(false);
    }

}
