// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: behaiv.proto

package tech.donau.behaiv.proto;

/**
 * <pre>
 * Communication messages
 * </pre>
 *
 * Protobuf type {@code Action}
 */
public  final class Action extends
    com.google.protobuf.GeneratedMessageLite<
        Action, Action.Builder> implements
    // @@protoc_insertion_point(message_implements:Action)
    ActionOrBuilder {
  private Action() {
    action_ = "";
    object_ = "";
    screenStack_ = emptyIntList();
  }
  public static final int LOCAL_ID_FIELD_NUMBER = 1;
  private long localId_;
  /**
   * <code>int64 local_id = 1;</code>
   * @return The localId.
   */
  @java.lang.Override
  public long getLocalId() {
    return localId_;
  }
  /**
   * <code>int64 local_id = 1;</code>
   * @param value The localId to set.
   */
  private void setLocalId(long value) {
    
    localId_ = value;
  }
  /**
   * <code>int64 local_id = 1;</code>
   */
  private void clearLocalId() {
    
    localId_ = 0L;
  }

  public static final int PREV_LOCAL_ID_FIELD_NUMBER = 2;
  private long prevLocalId_;
  /**
   * <code>int64 prev_local_id = 2;</code>
   * @return The prevLocalId.
   */
  @java.lang.Override
  public long getPrevLocalId() {
    return prevLocalId_;
  }
  /**
   * <code>int64 prev_local_id = 2;</code>
   * @param value The prevLocalId to set.
   */
  private void setPrevLocalId(long value) {
    
    prevLocalId_ = value;
  }
  /**
   * <code>int64 prev_local_id = 2;</code>
   */
  private void clearPrevLocalId() {
    
    prevLocalId_ = 0L;
  }

  public static final int ACTION_FIELD_NUMBER = 3;
  private java.lang.String action_;
  /**
   * <code>string action = 3;</code>
   * @return The action.
   */
  @java.lang.Override
  public java.lang.String getAction() {
    return action_;
  }
  /**
   * <code>string action = 3;</code>
   * @return The bytes for action.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getActionBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(action_);
  }
  /**
   * <code>string action = 3;</code>
   * @param value The action to set.
   */
  private void setAction(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    action_ = value;
  }
  /**
   * <code>string action = 3;</code>
   */
  private void clearAction() {
    
    action_ = getDefaultInstance().getAction();
  }
  /**
   * <code>string action = 3;</code>
   * @param value The bytes for action to set.
   */
  private void setActionBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    action_ = value.toStringUtf8();
  }

  public static final int OBJECT_FIELD_NUMBER = 4;
  private java.lang.String object_;
  /**
   * <code>string object = 4;</code>
   * @return The object.
   */
  @java.lang.Override
  public java.lang.String getObject() {
    return object_;
  }
  /**
   * <code>string object = 4;</code>
   * @return The bytes for object.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getObjectBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(object_);
  }
  /**
   * <code>string object = 4;</code>
   * @param value The object to set.
   */
  private void setObject(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    object_ = value;
  }
  /**
   * <code>string object = 4;</code>
   */
  private void clearObject() {
    
    object_ = getDefaultInstance().getObject();
  }
  /**
   * <code>string object = 4;</code>
   * @param value The bytes for object to set.
   */
  private void setObjectBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    object_ = value.toStringUtf8();
  }

  public static final int CURRENT_SCREEN_ID_FIELD_NUMBER = 5;
  private int currentScreenId_;
  /**
   * <code>int32 current_screen_id = 5;</code>
   * @return The currentScreenId.
   */
  @java.lang.Override
  public int getCurrentScreenId() {
    return currentScreenId_;
  }
  /**
   * <code>int32 current_screen_id = 5;</code>
   * @param value The currentScreenId to set.
   */
  private void setCurrentScreenId(int value) {
    
    currentScreenId_ = value;
  }
  /**
   * <code>int32 current_screen_id = 5;</code>
   */
  private void clearCurrentScreenId() {
    
    currentScreenId_ = 0;
  }

  public static final int SCREEN_STACK_FIELD_NUMBER = 6;
  private com.google.protobuf.Internal.IntList screenStack_;
  /**
   * <pre>
   *    repeated Event events = 7; TODO
   * </pre>
   *
   * <code>repeated int32 screen_stack = 6;</code>
   * @return A list containing the screenStack.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getScreenStackList() {
    return screenStack_;
  }
  /**
   * <pre>
   *    repeated Event events = 7; TODO
   * </pre>
   *
   * <code>repeated int32 screen_stack = 6;</code>
   * @return The count of screenStack.
   */
  @java.lang.Override
  public int getScreenStackCount() {
    return screenStack_.size();
  }
  /**
   * <pre>
   *    repeated Event events = 7; TODO
   * </pre>
   *
   * <code>repeated int32 screen_stack = 6;</code>
   * @param index The index of the element to return.
   * @return The screenStack at the given index.
   */
  @java.lang.Override
  public int getScreenStack(int index) {
    return screenStack_.getInt(index);
  }
  private int screenStackMemoizedSerializedSize = -1;
  private void ensureScreenStackIsMutable() {
    if (!screenStack_.isModifiable()) {
      screenStack_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(screenStack_);
     }
  }
  /**
   * <pre>
   *    repeated Event events = 7; TODO
   * </pre>
   *
   * <code>repeated int32 screen_stack = 6;</code>
   * @param index The index to set the value at.
   * @param value The screenStack to set.
   */
  private void setScreenStack(
      int index, int value) {
    ensureScreenStackIsMutable();
    screenStack_.setInt(index, value);
  }
  /**
   * <pre>
   *    repeated Event events = 7; TODO
   * </pre>
   *
   * <code>repeated int32 screen_stack = 6;</code>
   * @param value The screenStack to add.
   */
  private void addScreenStack(int value) {
    ensureScreenStackIsMutable();
    screenStack_.addInt(value);
  }
  /**
   * <pre>
   *    repeated Event events = 7; TODO
   * </pre>
   *
   * <code>repeated int32 screen_stack = 6;</code>
   * @param values The screenStack to add.
   */
  private void addAllScreenStack(
      java.lang.Iterable<? extends java.lang.Integer> values) {
    ensureScreenStackIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, screenStack_);
  }
  /**
   * <pre>
   *    repeated Event events = 7; TODO
   * </pre>
   *
   * <code>repeated int32 screen_stack = 6;</code>
   */
  private void clearScreenStack() {
    screenStack_ = emptyIntList();
  }

  public static final int ATTRIBUTES_FIELD_NUMBER = 8;
  private static final class AttributesDefaultEntryHolder {
    static final com.google.protobuf.MapEntryLite<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntryLite
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapFieldLite<
      java.lang.String, java.lang.String> attributes_ =
          com.google.protobuf.MapFieldLite.emptyMapField();
  private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.String>
  internalGetAttributes() {
    return attributes_;
  }
  private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.String>
  internalGetMutableAttributes() {
    if (!attributes_.isMutable()) {
      attributes_ = attributes_.mutableCopy();
    }
    return attributes_;
  }
  @java.lang.Override

  public int getAttributesCount() {
    return internalGetAttributes().size();
  }
  /**
   * <code>map&lt;string, string&gt; attributes = 8;</code>
   */
  @java.lang.Override

  public boolean containsAttributes(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetAttributes().containsKey(key);
  }
  /**
   * Use {@link #getAttributesMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getAttributes() {
    return getAttributesMap();
  }
  /**
   * <code>map&lt;string, string&gt; attributes = 8;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.String> getAttributesMap() {
    return java.util.Collections.unmodifiableMap(
        internalGetAttributes());
  }
  /**
   * <code>map&lt;string, string&gt; attributes = 8;</code>
   */
  @java.lang.Override

  public java.lang.String getAttributesOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetAttributes();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; attributes = 8;</code>
   */
  @java.lang.Override

  public java.lang.String getAttributesOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetAttributes();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }
  /**
   * <code>map&lt;string, string&gt; attributes = 8;</code>
   */
  private java.util.Map<java.lang.String, java.lang.String>
  getMutableAttributesMap() {
    return internalGetMutableAttributes();
  }

  public static tech.donau.behaiv.proto.Action parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static tech.donau.behaiv.proto.Action parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static tech.donau.behaiv.proto.Action parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static tech.donau.behaiv.proto.Action parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static tech.donau.behaiv.proto.Action parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static tech.donau.behaiv.proto.Action parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static tech.donau.behaiv.proto.Action parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static tech.donau.behaiv.proto.Action parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static tech.donau.behaiv.proto.Action parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static tech.donau.behaiv.proto.Action parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static tech.donau.behaiv.proto.Action parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static tech.donau.behaiv.proto.Action parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(tech.donau.behaiv.proto.Action prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Communication messages
   * </pre>
   *
   * Protobuf type {@code Action}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        tech.donau.behaiv.proto.Action, Builder> implements
      // @@protoc_insertion_point(builder_implements:Action)
      tech.donau.behaiv.proto.ActionOrBuilder {
    // Construct using tech.donau.behaiv.proto.Action.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>int64 local_id = 1;</code>
     * @return The localId.
     */
    @java.lang.Override
    public long getLocalId() {
      return instance.getLocalId();
    }
    /**
     * <code>int64 local_id = 1;</code>
     * @param value The localId to set.
     * @return This builder for chaining.
     */
    public Builder setLocalId(long value) {
      copyOnWrite();
      instance.setLocalId(value);
      return this;
    }
    /**
     * <code>int64 local_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLocalId() {
      copyOnWrite();
      instance.clearLocalId();
      return this;
    }

    /**
     * <code>int64 prev_local_id = 2;</code>
     * @return The prevLocalId.
     */
    @java.lang.Override
    public long getPrevLocalId() {
      return instance.getPrevLocalId();
    }
    /**
     * <code>int64 prev_local_id = 2;</code>
     * @param value The prevLocalId to set.
     * @return This builder for chaining.
     */
    public Builder setPrevLocalId(long value) {
      copyOnWrite();
      instance.setPrevLocalId(value);
      return this;
    }
    /**
     * <code>int64 prev_local_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrevLocalId() {
      copyOnWrite();
      instance.clearPrevLocalId();
      return this;
    }

    /**
     * <code>string action = 3;</code>
     * @return The action.
     */
    @java.lang.Override
    public java.lang.String getAction() {
      return instance.getAction();
    }
    /**
     * <code>string action = 3;</code>
     * @return The bytes for action.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getActionBytes() {
      return instance.getActionBytes();
    }
    /**
     * <code>string action = 3;</code>
     * @param value The action to set.
     * @return This builder for chaining.
     */
    public Builder setAction(
        java.lang.String value) {
      copyOnWrite();
      instance.setAction(value);
      return this;
    }
    /**
     * <code>string action = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAction() {
      copyOnWrite();
      instance.clearAction();
      return this;
    }
    /**
     * <code>string action = 3;</code>
     * @param value The bytes for action to set.
     * @return This builder for chaining.
     */
    public Builder setActionBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setActionBytes(value);
      return this;
    }

    /**
     * <code>string object = 4;</code>
     * @return The object.
     */
    @java.lang.Override
    public java.lang.String getObject() {
      return instance.getObject();
    }
    /**
     * <code>string object = 4;</code>
     * @return The bytes for object.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getObjectBytes() {
      return instance.getObjectBytes();
    }
    /**
     * <code>string object = 4;</code>
     * @param value The object to set.
     * @return This builder for chaining.
     */
    public Builder setObject(
        java.lang.String value) {
      copyOnWrite();
      instance.setObject(value);
      return this;
    }
    /**
     * <code>string object = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearObject() {
      copyOnWrite();
      instance.clearObject();
      return this;
    }
    /**
     * <code>string object = 4;</code>
     * @param value The bytes for object to set.
     * @return This builder for chaining.
     */
    public Builder setObjectBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setObjectBytes(value);
      return this;
    }

    /**
     * <code>int32 current_screen_id = 5;</code>
     * @return The currentScreenId.
     */
    @java.lang.Override
    public int getCurrentScreenId() {
      return instance.getCurrentScreenId();
    }
    /**
     * <code>int32 current_screen_id = 5;</code>
     * @param value The currentScreenId to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentScreenId(int value) {
      copyOnWrite();
      instance.setCurrentScreenId(value);
      return this;
    }
    /**
     * <code>int32 current_screen_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentScreenId() {
      copyOnWrite();
      instance.clearCurrentScreenId();
      return this;
    }

    /**
     * <pre>
     *    repeated Event events = 7; TODO
     * </pre>
     *
     * <code>repeated int32 screen_stack = 6;</code>
     * @return A list containing the screenStack.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getScreenStackList() {
      return java.util.Collections.unmodifiableList(
          instance.getScreenStackList());
    }
    /**
     * <pre>
     *    repeated Event events = 7; TODO
     * </pre>
     *
     * <code>repeated int32 screen_stack = 6;</code>
     * @return The count of screenStack.
     */
    @java.lang.Override
    public int getScreenStackCount() {
      return instance.getScreenStackCount();
    }
    /**
     * <pre>
     *    repeated Event events = 7; TODO
     * </pre>
     *
     * <code>repeated int32 screen_stack = 6;</code>
     * @param index The index of the element to return.
     * @return The screenStack at the given index.
     */
    @java.lang.Override
    public int getScreenStack(int index) {
      return instance.getScreenStack(index);
    }
    /**
     * <pre>
     *    repeated Event events = 7; TODO
     * </pre>
     *
     * <code>repeated int32 screen_stack = 6;</code>
     * @param value The screenStack to set.
     * @return This builder for chaining.
     */
    public Builder setScreenStack(
        int index, int value) {
      copyOnWrite();
      instance.setScreenStack(index, value);
      return this;
    }
    /**
     * <pre>
     *    repeated Event events = 7; TODO
     * </pre>
     *
     * <code>repeated int32 screen_stack = 6;</code>
     * @param value The screenStack to add.
     * @return This builder for chaining.
     */
    public Builder addScreenStack(int value) {
      copyOnWrite();
      instance.addScreenStack(value);
      return this;
    }
    /**
     * <pre>
     *    repeated Event events = 7; TODO
     * </pre>
     *
     * <code>repeated int32 screen_stack = 6;</code>
     * @param values The screenStack to add.
     * @return This builder for chaining.
     */
    public Builder addAllScreenStack(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      copyOnWrite();
      instance.addAllScreenStack(values);
      return this;
    }
    /**
     * <pre>
     *    repeated Event events = 7; TODO
     * </pre>
     *
     * <code>repeated int32 screen_stack = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearScreenStack() {
      copyOnWrite();
      instance.clearScreenStack();
      return this;
    }

    @java.lang.Override

    public int getAttributesCount() {
      return instance.getAttributesMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; attributes = 8;</code>
     */
    @java.lang.Override

    public boolean containsAttributes(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return instance.getAttributesMap().containsKey(key);
    }

    public Builder clearAttributes() {
      copyOnWrite();
      instance.getMutableAttributesMap().clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; attributes = 8;</code>
     */

    public Builder removeAttributes(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      copyOnWrite();
      instance.getMutableAttributesMap().remove(key);
      return this;
    }
    /**
     * Use {@link #getAttributesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getAttributes() {
      return getAttributesMap();
    }
    /**
     * <code>map&lt;string, string&gt; attributes = 8;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getAttributesMap() {
      return java.util.Collections.unmodifiableMap(
          instance.getAttributesMap());
    }
    /**
     * <code>map&lt;string, string&gt; attributes = 8;</code>
     */
    @java.lang.Override

    public java.lang.String getAttributesOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          instance.getAttributesMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; attributes = 8;</code>
     */
    @java.lang.Override

    public java.lang.String getAttributesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          instance.getAttributesMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    /**
     * <code>map&lt;string, string&gt; attributes = 8;</code>
     */
    public Builder putAttributes(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      copyOnWrite();
      instance.getMutableAttributesMap().put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; attributes = 8;</code>
     */
    public Builder putAllAttributes(
        java.util.Map<java.lang.String, java.lang.String> values) {
      copyOnWrite();
      instance.getMutableAttributesMap().putAll(values);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:Action)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new tech.donau.behaiv.proto.Action();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "localId_",
            "prevLocalId_",
            "action_",
            "object_",
            "currentScreenId_",
            "screenStack_",
            "attributes_",
            AttributesDefaultEntryHolder.defaultEntry,
          };
          java.lang.String info =
              "\u0000\u0007\u0000\u0000\u0001\b\u0007\u0001\u0001\u0000\u0001\u0002\u0002\u0002" +
              "\u0003\u0208\u0004\u0208\u0005\u0004\u0006\'\b2";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<tech.donau.behaiv.proto.Action> parser = PARSER;
        if (parser == null) {
          synchronized (tech.donau.behaiv.proto.Action.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<tech.donau.behaiv.proto.Action>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:Action)
  private static final tech.donau.behaiv.proto.Action DEFAULT_INSTANCE;
  static {
    Action defaultInstance = new Action();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Action.class, defaultInstance);
  }

  public static tech.donau.behaiv.proto.Action getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Action> PARSER;

  public static com.google.protobuf.Parser<Action> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

