// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: behaiv.proto

package tech.donau.behaiv.proto;

/**
 * <pre>
 * Communication messages
 * </pre>
 *
 * Protobuf type {@code Action}
 */
public  final class Action extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Action)
    ActionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Action.newBuilder() to construct.
  private Action(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Action() {
    action_ = "";
    object_ = "";
    screenStack_ = emptyIntList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Action();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Action(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            localId_ = input.readInt64();
            break;
          }
          case 16: {

            prevLocalId_ = input.readInt64();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            action_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            object_ = s;
            break;
          }
          case 40: {

            currentScreenId_ = input.readInt32();
            break;
          }
          case 48: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              screenStack_ = newIntList();
              mutable_bitField0_ |= 0x00000001;
            }
            screenStack_.addInt(input.readInt32());
            break;
          }
          case 50: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              screenStack_ = newIntList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              screenStack_.addInt(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          case 66: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              attributes_ = com.google.protobuf.MapField.newMapField(
                  AttributesDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000002;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            attributes__ = input.readMessage(
                AttributesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            attributes_.getMutableMap().put(
                attributes__.getKey(), attributes__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        screenStack_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return tech.donau.behaiv.proto.Behaiv.internal_static_Action_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 8:
        return internalGetAttributes();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return tech.donau.behaiv.proto.Behaiv.internal_static_Action_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            tech.donau.behaiv.proto.Action.class, tech.donau.behaiv.proto.Action.Builder.class);
  }

  public static final int LOCAL_ID_FIELD_NUMBER = 1;
  private long localId_;
  /**
   * <code>int64 local_id = 1;</code>
   * @return The localId.
   */
  public long getLocalId() {
    return localId_;
  }

  public static final int PREV_LOCAL_ID_FIELD_NUMBER = 2;
  private long prevLocalId_;
  /**
   * <code>int64 prev_local_id = 2;</code>
   * @return The prevLocalId.
   */
  public long getPrevLocalId() {
    return prevLocalId_;
  }

  public static final int ACTION_FIELD_NUMBER = 3;
  private volatile java.lang.Object action_;
  /**
   * <code>string action = 3;</code>
   * @return The action.
   */
  public java.lang.String getAction() {
    java.lang.Object ref = action_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      action_ = s;
      return s;
    }
  }
  /**
   * <code>string action = 3;</code>
   * @return The bytes for action.
   */
  public com.google.protobuf.ByteString
      getActionBytes() {
    java.lang.Object ref = action_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      action_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OBJECT_FIELD_NUMBER = 4;
  private volatile java.lang.Object object_;
  /**
   * <code>string object = 4;</code>
   * @return The object.
   */
  public java.lang.String getObject() {
    java.lang.Object ref = object_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      object_ = s;
      return s;
    }
  }
  /**
   * <code>string object = 4;</code>
   * @return The bytes for object.
   */
  public com.google.protobuf.ByteString
      getObjectBytes() {
    java.lang.Object ref = object_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      object_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CURRENT_SCREEN_ID_FIELD_NUMBER = 5;
  private int currentScreenId_;
  /**
   * <code>int32 current_screen_id = 5;</code>
   * @return The currentScreenId.
   */
  public int getCurrentScreenId() {
    return currentScreenId_;
  }

  public static final int SCREEN_STACK_FIELD_NUMBER = 6;
  private com.google.protobuf.Internal.IntList screenStack_;
  /**
   * <pre>
   *    repeated Event events = 7; TODO
   * </pre>
   *
   * <code>repeated int32 screen_stack = 6;</code>
   * @return A list containing the screenStack.
   */
  public java.util.List<java.lang.Integer>
      getScreenStackList() {
    return screenStack_;
  }
  /**
   * <pre>
   *    repeated Event events = 7; TODO
   * </pre>
   *
   * <code>repeated int32 screen_stack = 6;</code>
   * @return The count of screenStack.
   */
  public int getScreenStackCount() {
    return screenStack_.size();
  }
  /**
   * <pre>
   *    repeated Event events = 7; TODO
   * </pre>
   *
   * <code>repeated int32 screen_stack = 6;</code>
   * @param index The index of the element to return.
   * @return The screenStack at the given index.
   */
  public int getScreenStack(int index) {
    return screenStack_.getInt(index);
  }
  private int screenStackMemoizedSerializedSize = -1;

  public static final int ATTRIBUTES_FIELD_NUMBER = 8;
  private static final class AttributesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                tech.donau.behaiv.proto.Behaiv.internal_static_Action_AttributesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> attributes_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetAttributes() {
    if (attributes_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          AttributesDefaultEntryHolder.defaultEntry);
    }
    return attributes_;
  }

  public int getAttributesCount() {
    return internalGetAttributes().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; attributes = 8;</code>
   */

  public boolean containsAttributes(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetAttributes().getMap().containsKey(key);
  }
  /**
   * Use {@link #getAttributesMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getAttributes() {
    return getAttributesMap();
  }
  /**
   * <code>map&lt;string, string&gt; attributes = 8;</code>
   */

  public java.util.Map<java.lang.String, java.lang.String> getAttributesMap() {
    return internalGetAttributes().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; attributes = 8;</code>
   */

  public java.lang.String getAttributesOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetAttributes().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; attributes = 8;</code>
   */

  public java.lang.String getAttributesOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetAttributes().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (localId_ != 0L) {
      output.writeInt64(1, localId_);
    }
    if (prevLocalId_ != 0L) {
      output.writeInt64(2, prevLocalId_);
    }
    if (!getActionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, action_);
    }
    if (!getObjectBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, object_);
    }
    if (currentScreenId_ != 0) {
      output.writeInt32(5, currentScreenId_);
    }
    if (getScreenStackList().size() > 0) {
      output.writeUInt32NoTag(50);
      output.writeUInt32NoTag(screenStackMemoizedSerializedSize);
    }
    for (int i = 0; i < screenStack_.size(); i++) {
      output.writeInt32NoTag(screenStack_.getInt(i));
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetAttributes(),
        AttributesDefaultEntryHolder.defaultEntry,
        8);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (localId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, localId_);
    }
    if (prevLocalId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, prevLocalId_);
    }
    if (!getActionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, action_);
    }
    if (!getObjectBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, object_);
    }
    if (currentScreenId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, currentScreenId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < screenStack_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(screenStack_.getInt(i));
      }
      size += dataSize;
      if (!getScreenStackList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      screenStackMemoizedSerializedSize = dataSize;
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetAttributes().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      attributes__ = AttributesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, attributes__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof tech.donau.behaiv.proto.Action)) {
      return super.equals(obj);
    }
    tech.donau.behaiv.proto.Action other = (tech.donau.behaiv.proto.Action) obj;

    if (getLocalId()
        != other.getLocalId()) return false;
    if (getPrevLocalId()
        != other.getPrevLocalId()) return false;
    if (!getAction()
        .equals(other.getAction())) return false;
    if (!getObject()
        .equals(other.getObject())) return false;
    if (getCurrentScreenId()
        != other.getCurrentScreenId()) return false;
    if (!getScreenStackList()
        .equals(other.getScreenStackList())) return false;
    if (!internalGetAttributes().equals(
        other.internalGetAttributes())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LOCAL_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLocalId());
    hash = (37 * hash) + PREV_LOCAL_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPrevLocalId());
    hash = (37 * hash) + ACTION_FIELD_NUMBER;
    hash = (53 * hash) + getAction().hashCode();
    hash = (37 * hash) + OBJECT_FIELD_NUMBER;
    hash = (53 * hash) + getObject().hashCode();
    hash = (37 * hash) + CURRENT_SCREEN_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCurrentScreenId();
    if (getScreenStackCount() > 0) {
      hash = (37 * hash) + SCREEN_STACK_FIELD_NUMBER;
      hash = (53 * hash) + getScreenStackList().hashCode();
    }
    if (!internalGetAttributes().getMap().isEmpty()) {
      hash = (37 * hash) + ATTRIBUTES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetAttributes().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static tech.donau.behaiv.proto.Action parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tech.donau.behaiv.proto.Action parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tech.donau.behaiv.proto.Action parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tech.donau.behaiv.proto.Action parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tech.donau.behaiv.proto.Action parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tech.donau.behaiv.proto.Action parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tech.donau.behaiv.proto.Action parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static tech.donau.behaiv.proto.Action parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static tech.donau.behaiv.proto.Action parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static tech.donau.behaiv.proto.Action parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static tech.donau.behaiv.proto.Action parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static tech.donau.behaiv.proto.Action parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(tech.donau.behaiv.proto.Action prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Communication messages
   * </pre>
   *
   * Protobuf type {@code Action}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Action)
      tech.donau.behaiv.proto.ActionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tech.donau.behaiv.proto.Behaiv.internal_static_Action_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 8:
          return internalGetAttributes();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 8:
          return internalGetMutableAttributes();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tech.donau.behaiv.proto.Behaiv.internal_static_Action_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tech.donau.behaiv.proto.Action.class, tech.donau.behaiv.proto.Action.Builder.class);
    }

    // Construct using tech.donau.behaiv.proto.Action.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      localId_ = 0L;

      prevLocalId_ = 0L;

      action_ = "";

      object_ = "";

      currentScreenId_ = 0;

      screenStack_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      internalGetMutableAttributes().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return tech.donau.behaiv.proto.Behaiv.internal_static_Action_descriptor;
    }

    @java.lang.Override
    public tech.donau.behaiv.proto.Action getDefaultInstanceForType() {
      return tech.donau.behaiv.proto.Action.getDefaultInstance();
    }

    @java.lang.Override
    public tech.donau.behaiv.proto.Action build() {
      tech.donau.behaiv.proto.Action result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public tech.donau.behaiv.proto.Action buildPartial() {
      tech.donau.behaiv.proto.Action result = new tech.donau.behaiv.proto.Action(this);
      int from_bitField0_ = bitField0_;
      result.localId_ = localId_;
      result.prevLocalId_ = prevLocalId_;
      result.action_ = action_;
      result.object_ = object_;
      result.currentScreenId_ = currentScreenId_;
      if (((bitField0_ & 0x00000001) != 0)) {
        screenStack_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.screenStack_ = screenStack_;
      result.attributes_ = internalGetAttributes();
      result.attributes_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof tech.donau.behaiv.proto.Action) {
        return mergeFrom((tech.donau.behaiv.proto.Action)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(tech.donau.behaiv.proto.Action other) {
      if (other == tech.donau.behaiv.proto.Action.getDefaultInstance()) return this;
      if (other.getLocalId() != 0L) {
        setLocalId(other.getLocalId());
      }
      if (other.getPrevLocalId() != 0L) {
        setPrevLocalId(other.getPrevLocalId());
      }
      if (!other.getAction().isEmpty()) {
        action_ = other.action_;
        onChanged();
      }
      if (!other.getObject().isEmpty()) {
        object_ = other.object_;
        onChanged();
      }
      if (other.getCurrentScreenId() != 0) {
        setCurrentScreenId(other.getCurrentScreenId());
      }
      if (!other.screenStack_.isEmpty()) {
        if (screenStack_.isEmpty()) {
          screenStack_ = other.screenStack_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureScreenStackIsMutable();
          screenStack_.addAll(other.screenStack_);
        }
        onChanged();
      }
      internalGetMutableAttributes().mergeFrom(
          other.internalGetAttributes());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      tech.donau.behaiv.proto.Action parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (tech.donau.behaiv.proto.Action) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long localId_ ;
    /**
     * <code>int64 local_id = 1;</code>
     * @return The localId.
     */
    public long getLocalId() {
      return localId_;
    }
    /**
     * <code>int64 local_id = 1;</code>
     * @param value The localId to set.
     * @return This builder for chaining.
     */
    public Builder setLocalId(long value) {
      
      localId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 local_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLocalId() {
      
      localId_ = 0L;
      onChanged();
      return this;
    }

    private long prevLocalId_ ;
    /**
     * <code>int64 prev_local_id = 2;</code>
     * @return The prevLocalId.
     */
    public long getPrevLocalId() {
      return prevLocalId_;
    }
    /**
     * <code>int64 prev_local_id = 2;</code>
     * @param value The prevLocalId to set.
     * @return This builder for chaining.
     */
    public Builder setPrevLocalId(long value) {
      
      prevLocalId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 prev_local_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrevLocalId() {
      
      prevLocalId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object action_ = "";
    /**
     * <code>string action = 3;</code>
     * @return The action.
     */
    public java.lang.String getAction() {
      java.lang.Object ref = action_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        action_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string action = 3;</code>
     * @return The bytes for action.
     */
    public com.google.protobuf.ByteString
        getActionBytes() {
      java.lang.Object ref = action_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        action_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string action = 3;</code>
     * @param value The action to set.
     * @return This builder for chaining.
     */
    public Builder setAction(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      action_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string action = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAction() {
      
      action_ = getDefaultInstance().getAction();
      onChanged();
      return this;
    }
    /**
     * <code>string action = 3;</code>
     * @param value The bytes for action to set.
     * @return This builder for chaining.
     */
    public Builder setActionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      action_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object object_ = "";
    /**
     * <code>string object = 4;</code>
     * @return The object.
     */
    public java.lang.String getObject() {
      java.lang.Object ref = object_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        object_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string object = 4;</code>
     * @return The bytes for object.
     */
    public com.google.protobuf.ByteString
        getObjectBytes() {
      java.lang.Object ref = object_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        object_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string object = 4;</code>
     * @param value The object to set.
     * @return This builder for chaining.
     */
    public Builder setObject(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      object_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string object = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearObject() {
      
      object_ = getDefaultInstance().getObject();
      onChanged();
      return this;
    }
    /**
     * <code>string object = 4;</code>
     * @param value The bytes for object to set.
     * @return This builder for chaining.
     */
    public Builder setObjectBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      object_ = value;
      onChanged();
      return this;
    }

    private int currentScreenId_ ;
    /**
     * <code>int32 current_screen_id = 5;</code>
     * @return The currentScreenId.
     */
    public int getCurrentScreenId() {
      return currentScreenId_;
    }
    /**
     * <code>int32 current_screen_id = 5;</code>
     * @param value The currentScreenId to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentScreenId(int value) {
      
      currentScreenId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 current_screen_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentScreenId() {
      
      currentScreenId_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList screenStack_ = emptyIntList();
    private void ensureScreenStackIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        screenStack_ = mutableCopy(screenStack_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     *    repeated Event events = 7; TODO
     * </pre>
     *
     * <code>repeated int32 screen_stack = 6;</code>
     * @return A list containing the screenStack.
     */
    public java.util.List<java.lang.Integer>
        getScreenStackList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(screenStack_) : screenStack_;
    }
    /**
     * <pre>
     *    repeated Event events = 7; TODO
     * </pre>
     *
     * <code>repeated int32 screen_stack = 6;</code>
     * @return The count of screenStack.
     */
    public int getScreenStackCount() {
      return screenStack_.size();
    }
    /**
     * <pre>
     *    repeated Event events = 7; TODO
     * </pre>
     *
     * <code>repeated int32 screen_stack = 6;</code>
     * @param index The index of the element to return.
     * @return The screenStack at the given index.
     */
    public int getScreenStack(int index) {
      return screenStack_.getInt(index);
    }
    /**
     * <pre>
     *    repeated Event events = 7; TODO
     * </pre>
     *
     * <code>repeated int32 screen_stack = 6;</code>
     * @param index The index to set the value at.
     * @param value The screenStack to set.
     * @return This builder for chaining.
     */
    public Builder setScreenStack(
        int index, int value) {
      ensureScreenStackIsMutable();
      screenStack_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *    repeated Event events = 7; TODO
     * </pre>
     *
     * <code>repeated int32 screen_stack = 6;</code>
     * @param value The screenStack to add.
     * @return This builder for chaining.
     */
    public Builder addScreenStack(int value) {
      ensureScreenStackIsMutable();
      screenStack_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *    repeated Event events = 7; TODO
     * </pre>
     *
     * <code>repeated int32 screen_stack = 6;</code>
     * @param values The screenStack to add.
     * @return This builder for chaining.
     */
    public Builder addAllScreenStack(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureScreenStackIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, screenStack_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *    repeated Event events = 7; TODO
     * </pre>
     *
     * <code>repeated int32 screen_stack = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearScreenStack() {
      screenStack_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> attributes_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetAttributes() {
      if (attributes_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AttributesDefaultEntryHolder.defaultEntry);
      }
      return attributes_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableAttributes() {
      onChanged();;
      if (attributes_ == null) {
        attributes_ = com.google.protobuf.MapField.newMapField(
            AttributesDefaultEntryHolder.defaultEntry);
      }
      if (!attributes_.isMutable()) {
        attributes_ = attributes_.copy();
      }
      return attributes_;
    }

    public int getAttributesCount() {
      return internalGetAttributes().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; attributes = 8;</code>
     */

    public boolean containsAttributes(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetAttributes().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAttributesMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getAttributes() {
      return getAttributesMap();
    }
    /**
     * <code>map&lt;string, string&gt; attributes = 8;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getAttributesMap() {
      return internalGetAttributes().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; attributes = 8;</code>
     */

    public java.lang.String getAttributesOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAttributes().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; attributes = 8;</code>
     */

    public java.lang.String getAttributesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAttributes().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearAttributes() {
      internalGetMutableAttributes().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; attributes = 8;</code>
     */

    public Builder removeAttributes(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableAttributes().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableAttributes() {
      return internalGetMutableAttributes().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; attributes = 8;</code>
     */
    public Builder putAttributes(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableAttributes().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; attributes = 8;</code>
     */

    public Builder putAllAttributes(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableAttributes().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Action)
  }

  // @@protoc_insertion_point(class_scope:Action)
  private static final tech.donau.behaiv.proto.Action DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new tech.donau.behaiv.proto.Action();
  }

  public static tech.donau.behaiv.proto.Action getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Action>
      PARSER = new com.google.protobuf.AbstractParser<Action>() {
    @java.lang.Override
    public Action parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Action(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Action> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Action> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public tech.donau.behaiv.proto.Action getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

