// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: behaiv.proto

package tech.donau.behaiv.proto;

public interface DataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Data)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 2;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <code>string key = 2;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>double value = 3;</code>
   * @return The value.
   */
  double getValue();
}
