// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: behaiv.proto

package tech.donau.behaiv.proto;

public interface PredictionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Prediction)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .Data data = 1;</code>
   */
  java.util.List<tech.donau.behaiv.proto.Data> 
      getDataList();
  /**
   * <code>repeated .Data data = 1;</code>
   */
  tech.donau.behaiv.proto.Data getData(int index);
  /**
   * <code>repeated .Data data = 1;</code>
   */
  int getDataCount();

  /**
   * <code>string label = 2;</code>
   * @return The label.
   */
  java.lang.String getLabel();
  /**
   * <code>string label = 2;</code>
   * @return The bytes for label.
   */
  com.google.protobuf.ByteString
      getLabelBytes();
}
