// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: behaiv.proto

package tech.donau.behaiv.proto;

public interface PredictionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Prediction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Data data = 1;</code>
   */
  java.util.List<tech.donau.behaiv.proto.Data> 
      getDataList();
  /**
   * <code>repeated .Data data = 1;</code>
   */
  tech.donau.behaiv.proto.Data getData(int index);
  /**
   * <code>repeated .Data data = 1;</code>
   */
  int getDataCount();
  /**
   * <code>repeated .Data data = 1;</code>
   */
  java.util.List<? extends tech.donau.behaiv.proto.DataOrBuilder> 
      getDataOrBuilderList();
  /**
   * <code>repeated .Data data = 1;</code>
   */
  tech.donau.behaiv.proto.DataOrBuilder getDataOrBuilder(
      int index);

  /**
   * <code>string prediction = 2;</code>
   * @return The prediction.
   */
  java.lang.String getPrediction();
  /**
   * <code>string prediction = 2;</code>
   * @return The bytes for prediction.
   */
  com.google.protobuf.ByteString
      getPredictionBytes();
}
