// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: behaiv.proto

package tech.donau.behaiv.proto;

/**
 * Protobuf type {@code PredictionSet}
 */
public  final class PredictionSet extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PredictionSet)
    PredictionSetOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PredictionSet.newBuilder() to construct.
  private PredictionSet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PredictionSet() {
    prediction_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PredictionSet();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PredictionSet(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              prediction_ = new java.util.ArrayList<tech.donau.behaiv.proto.Prediction>();
              mutable_bitField0_ |= 0x00000001;
            }
            prediction_.add(
                input.readMessage(tech.donau.behaiv.proto.Prediction.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        prediction_ = java.util.Collections.unmodifiableList(prediction_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return tech.donau.behaiv.proto.Behaiv.internal_static_PredictionSet_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return tech.donau.behaiv.proto.Behaiv.internal_static_PredictionSet_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            tech.donau.behaiv.proto.PredictionSet.class, tech.donau.behaiv.proto.PredictionSet.Builder.class);
  }

  public static final int PREDICTION_FIELD_NUMBER = 1;
  private java.util.List<tech.donau.behaiv.proto.Prediction> prediction_;
  /**
   * <code>repeated .Prediction prediction = 1;</code>
   */
  public java.util.List<tech.donau.behaiv.proto.Prediction> getPredictionList() {
    return prediction_;
  }
  /**
   * <code>repeated .Prediction prediction = 1;</code>
   */
  public java.util.List<? extends tech.donau.behaiv.proto.PredictionOrBuilder> 
      getPredictionOrBuilderList() {
    return prediction_;
  }
  /**
   * <code>repeated .Prediction prediction = 1;</code>
   */
  public int getPredictionCount() {
    return prediction_.size();
  }
  /**
   * <code>repeated .Prediction prediction = 1;</code>
   */
  public tech.donau.behaiv.proto.Prediction getPrediction(int index) {
    return prediction_.get(index);
  }
  /**
   * <code>repeated .Prediction prediction = 1;</code>
   */
  public tech.donau.behaiv.proto.PredictionOrBuilder getPredictionOrBuilder(
      int index) {
    return prediction_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < prediction_.size(); i++) {
      output.writeMessage(1, prediction_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < prediction_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, prediction_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof tech.donau.behaiv.proto.PredictionSet)) {
      return super.equals(obj);
    }
    tech.donau.behaiv.proto.PredictionSet other = (tech.donau.behaiv.proto.PredictionSet) obj;

    if (!getPredictionList()
        .equals(other.getPredictionList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPredictionCount() > 0) {
      hash = (37 * hash) + PREDICTION_FIELD_NUMBER;
      hash = (53 * hash) + getPredictionList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static tech.donau.behaiv.proto.PredictionSet parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tech.donau.behaiv.proto.PredictionSet parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tech.donau.behaiv.proto.PredictionSet parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tech.donau.behaiv.proto.PredictionSet parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tech.donau.behaiv.proto.PredictionSet parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tech.donau.behaiv.proto.PredictionSet parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tech.donau.behaiv.proto.PredictionSet parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static tech.donau.behaiv.proto.PredictionSet parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static tech.donau.behaiv.proto.PredictionSet parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static tech.donau.behaiv.proto.PredictionSet parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static tech.donau.behaiv.proto.PredictionSet parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static tech.donau.behaiv.proto.PredictionSet parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(tech.donau.behaiv.proto.PredictionSet prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PredictionSet}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PredictionSet)
      tech.donau.behaiv.proto.PredictionSetOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tech.donau.behaiv.proto.Behaiv.internal_static_PredictionSet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tech.donau.behaiv.proto.Behaiv.internal_static_PredictionSet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tech.donau.behaiv.proto.PredictionSet.class, tech.donau.behaiv.proto.PredictionSet.Builder.class);
    }

    // Construct using tech.donau.behaiv.proto.PredictionSet.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPredictionFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (predictionBuilder_ == null) {
        prediction_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        predictionBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return tech.donau.behaiv.proto.Behaiv.internal_static_PredictionSet_descriptor;
    }

    @java.lang.Override
    public tech.donau.behaiv.proto.PredictionSet getDefaultInstanceForType() {
      return tech.donau.behaiv.proto.PredictionSet.getDefaultInstance();
    }

    @java.lang.Override
    public tech.donau.behaiv.proto.PredictionSet build() {
      tech.donau.behaiv.proto.PredictionSet result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public tech.donau.behaiv.proto.PredictionSet buildPartial() {
      tech.donau.behaiv.proto.PredictionSet result = new tech.donau.behaiv.proto.PredictionSet(this);
      int from_bitField0_ = bitField0_;
      if (predictionBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          prediction_ = java.util.Collections.unmodifiableList(prediction_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.prediction_ = prediction_;
      } else {
        result.prediction_ = predictionBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof tech.donau.behaiv.proto.PredictionSet) {
        return mergeFrom((tech.donau.behaiv.proto.PredictionSet)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(tech.donau.behaiv.proto.PredictionSet other) {
      if (other == tech.donau.behaiv.proto.PredictionSet.getDefaultInstance()) return this;
      if (predictionBuilder_ == null) {
        if (!other.prediction_.isEmpty()) {
          if (prediction_.isEmpty()) {
            prediction_ = other.prediction_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePredictionIsMutable();
            prediction_.addAll(other.prediction_);
          }
          onChanged();
        }
      } else {
        if (!other.prediction_.isEmpty()) {
          if (predictionBuilder_.isEmpty()) {
            predictionBuilder_.dispose();
            predictionBuilder_ = null;
            prediction_ = other.prediction_;
            bitField0_ = (bitField0_ & ~0x00000001);
            predictionBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPredictionFieldBuilder() : null;
          } else {
            predictionBuilder_.addAllMessages(other.prediction_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      tech.donau.behaiv.proto.PredictionSet parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (tech.donau.behaiv.proto.PredictionSet) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<tech.donau.behaiv.proto.Prediction> prediction_ =
      java.util.Collections.emptyList();
    private void ensurePredictionIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        prediction_ = new java.util.ArrayList<tech.donau.behaiv.proto.Prediction>(prediction_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        tech.donau.behaiv.proto.Prediction, tech.donau.behaiv.proto.Prediction.Builder, tech.donau.behaiv.proto.PredictionOrBuilder> predictionBuilder_;

    /**
     * <code>repeated .Prediction prediction = 1;</code>
     */
    public java.util.List<tech.donau.behaiv.proto.Prediction> getPredictionList() {
      if (predictionBuilder_ == null) {
        return java.util.Collections.unmodifiableList(prediction_);
      } else {
        return predictionBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Prediction prediction = 1;</code>
     */
    public int getPredictionCount() {
      if (predictionBuilder_ == null) {
        return prediction_.size();
      } else {
        return predictionBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Prediction prediction = 1;</code>
     */
    public tech.donau.behaiv.proto.Prediction getPrediction(int index) {
      if (predictionBuilder_ == null) {
        return prediction_.get(index);
      } else {
        return predictionBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Prediction prediction = 1;</code>
     */
    public Builder setPrediction(
        int index, tech.donau.behaiv.proto.Prediction value) {
      if (predictionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePredictionIsMutable();
        prediction_.set(index, value);
        onChanged();
      } else {
        predictionBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Prediction prediction = 1;</code>
     */
    public Builder setPrediction(
        int index, tech.donau.behaiv.proto.Prediction.Builder builderForValue) {
      if (predictionBuilder_ == null) {
        ensurePredictionIsMutable();
        prediction_.set(index, builderForValue.build());
        onChanged();
      } else {
        predictionBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Prediction prediction = 1;</code>
     */
    public Builder addPrediction(tech.donau.behaiv.proto.Prediction value) {
      if (predictionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePredictionIsMutable();
        prediction_.add(value);
        onChanged();
      } else {
        predictionBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Prediction prediction = 1;</code>
     */
    public Builder addPrediction(
        int index, tech.donau.behaiv.proto.Prediction value) {
      if (predictionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePredictionIsMutable();
        prediction_.add(index, value);
        onChanged();
      } else {
        predictionBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Prediction prediction = 1;</code>
     */
    public Builder addPrediction(
        tech.donau.behaiv.proto.Prediction.Builder builderForValue) {
      if (predictionBuilder_ == null) {
        ensurePredictionIsMutable();
        prediction_.add(builderForValue.build());
        onChanged();
      } else {
        predictionBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Prediction prediction = 1;</code>
     */
    public Builder addPrediction(
        int index, tech.donau.behaiv.proto.Prediction.Builder builderForValue) {
      if (predictionBuilder_ == null) {
        ensurePredictionIsMutable();
        prediction_.add(index, builderForValue.build());
        onChanged();
      } else {
        predictionBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Prediction prediction = 1;</code>
     */
    public Builder addAllPrediction(
        java.lang.Iterable<? extends tech.donau.behaiv.proto.Prediction> values) {
      if (predictionBuilder_ == null) {
        ensurePredictionIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, prediction_);
        onChanged();
      } else {
        predictionBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Prediction prediction = 1;</code>
     */
    public Builder clearPrediction() {
      if (predictionBuilder_ == null) {
        prediction_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        predictionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Prediction prediction = 1;</code>
     */
    public Builder removePrediction(int index) {
      if (predictionBuilder_ == null) {
        ensurePredictionIsMutable();
        prediction_.remove(index);
        onChanged();
      } else {
        predictionBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Prediction prediction = 1;</code>
     */
    public tech.donau.behaiv.proto.Prediction.Builder getPredictionBuilder(
        int index) {
      return getPredictionFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Prediction prediction = 1;</code>
     */
    public tech.donau.behaiv.proto.PredictionOrBuilder getPredictionOrBuilder(
        int index) {
      if (predictionBuilder_ == null) {
        return prediction_.get(index);  } else {
        return predictionBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Prediction prediction = 1;</code>
     */
    public java.util.List<? extends tech.donau.behaiv.proto.PredictionOrBuilder> 
         getPredictionOrBuilderList() {
      if (predictionBuilder_ != null) {
        return predictionBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(prediction_);
      }
    }
    /**
     * <code>repeated .Prediction prediction = 1;</code>
     */
    public tech.donau.behaiv.proto.Prediction.Builder addPredictionBuilder() {
      return getPredictionFieldBuilder().addBuilder(
          tech.donau.behaiv.proto.Prediction.getDefaultInstance());
    }
    /**
     * <code>repeated .Prediction prediction = 1;</code>
     */
    public tech.donau.behaiv.proto.Prediction.Builder addPredictionBuilder(
        int index) {
      return getPredictionFieldBuilder().addBuilder(
          index, tech.donau.behaiv.proto.Prediction.getDefaultInstance());
    }
    /**
     * <code>repeated .Prediction prediction = 1;</code>
     */
    public java.util.List<tech.donau.behaiv.proto.Prediction.Builder> 
         getPredictionBuilderList() {
      return getPredictionFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        tech.donau.behaiv.proto.Prediction, tech.donau.behaiv.proto.Prediction.Builder, tech.donau.behaiv.proto.PredictionOrBuilder> 
        getPredictionFieldBuilder() {
      if (predictionBuilder_ == null) {
        predictionBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            tech.donau.behaiv.proto.Prediction, tech.donau.behaiv.proto.Prediction.Builder, tech.donau.behaiv.proto.PredictionOrBuilder>(
                prediction_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        prediction_ = null;
      }
      return predictionBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PredictionSet)
  }

  // @@protoc_insertion_point(class_scope:PredictionSet)
  private static final tech.donau.behaiv.proto.PredictionSet DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new tech.donau.behaiv.proto.PredictionSet();
  }

  public static tech.donau.behaiv.proto.PredictionSet getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PredictionSet>
      PARSER = new com.google.protobuf.AbstractParser<PredictionSet>() {
    @java.lang.Override
    public PredictionSet parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PredictionSet(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PredictionSet> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PredictionSet> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public tech.donau.behaiv.proto.PredictionSet getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

