// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: behaiv.proto

package tech.donau.behaiv.proto;

public interface PredictionSetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PredictionSet)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .Prediction prediction = 1;</code>
   */
  java.util.List<tech.donau.behaiv.proto.Prediction> 
      getPredictionList();
  /**
   * <code>repeated .Prediction prediction = 1;</code>
   */
  tech.donau.behaiv.proto.Prediction getPrediction(int index);
  /**
   * <code>repeated .Prediction prediction = 1;</code>
   */
  int getPredictionCount();

  /**
   * <code>bool dynamicColumns = 2;</code>
   * @return The dynamicColumns.
   */
  boolean getDynamicColumns();
}
