// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: behaiv.proto

package tech.donau.behaiv.proto;

/**
 * Protobuf type {@code PredictionSet}
 */
public  final class PredictionSet extends
    com.google.protobuf.GeneratedMessageLite<
        PredictionSet, PredictionSet.Builder> implements
    // @@protoc_insertion_point(message_implements:PredictionSet)
    PredictionSetOrBuilder {
  private PredictionSet() {
    prediction_ = emptyProtobufList();
  }
  public static final int PREDICTION_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<tech.donau.behaiv.proto.Prediction> prediction_;
  /**
   * <code>repeated .Prediction prediction = 1;</code>
   */
  @java.lang.Override
  public java.util.List<tech.donau.behaiv.proto.Prediction> getPredictionList() {
    return prediction_;
  }
  /**
   * <code>repeated .Prediction prediction = 1;</code>
   */
  public java.util.List<? extends tech.donau.behaiv.proto.PredictionOrBuilder> 
      getPredictionOrBuilderList() {
    return prediction_;
  }
  /**
   * <code>repeated .Prediction prediction = 1;</code>
   */
  @java.lang.Override
  public int getPredictionCount() {
    return prediction_.size();
  }
  /**
   * <code>repeated .Prediction prediction = 1;</code>
   */
  @java.lang.Override
  public tech.donau.behaiv.proto.Prediction getPrediction(int index) {
    return prediction_.get(index);
  }
  /**
   * <code>repeated .Prediction prediction = 1;</code>
   */
  public tech.donau.behaiv.proto.PredictionOrBuilder getPredictionOrBuilder(
      int index) {
    return prediction_.get(index);
  }
  private void ensurePredictionIsMutable() {
    if (!prediction_.isModifiable()) {
      prediction_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(prediction_);
     }
  }

  /**
   * <code>repeated .Prediction prediction = 1;</code>
   */
  private void setPrediction(
      int index, tech.donau.behaiv.proto.Prediction value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensurePredictionIsMutable();
    prediction_.set(index, value);
  }
  /**
   * <code>repeated .Prediction prediction = 1;</code>
   */
  private void setPrediction(
      int index, tech.donau.behaiv.proto.Prediction.Builder builderForValue) {
    ensurePredictionIsMutable();
    prediction_.set(index, builderForValue.build());
  }
  /**
   * <code>repeated .Prediction prediction = 1;</code>
   */
  private void addPrediction(tech.donau.behaiv.proto.Prediction value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensurePredictionIsMutable();
    prediction_.add(value);
  }
  /**
   * <code>repeated .Prediction prediction = 1;</code>
   */
  private void addPrediction(
      int index, tech.donau.behaiv.proto.Prediction value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensurePredictionIsMutable();
    prediction_.add(index, value);
  }
  /**
   * <code>repeated .Prediction prediction = 1;</code>
   */
  private void addPrediction(
      tech.donau.behaiv.proto.Prediction.Builder builderForValue) {
    ensurePredictionIsMutable();
    prediction_.add(builderForValue.build());
  }
  /**
   * <code>repeated .Prediction prediction = 1;</code>
   */
  private void addPrediction(
      int index, tech.donau.behaiv.proto.Prediction.Builder builderForValue) {
    ensurePredictionIsMutable();
    prediction_.add(index, builderForValue.build());
  }
  /**
   * <code>repeated .Prediction prediction = 1;</code>
   */
  private void addAllPrediction(
      java.lang.Iterable<? extends tech.donau.behaiv.proto.Prediction> values) {
    ensurePredictionIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, prediction_);
  }
  /**
   * <code>repeated .Prediction prediction = 1;</code>
   */
  private void clearPrediction() {
    prediction_ = emptyProtobufList();
  }
  /**
   * <code>repeated .Prediction prediction = 1;</code>
   */
  private void removePrediction(int index) {
    ensurePredictionIsMutable();
    prediction_.remove(index);
  }

  public static final int DYNAMICCOLUMNS_FIELD_NUMBER = 2;
  private boolean dynamicColumns_;
  /**
   * <code>bool dynamicColumns = 2;</code>
   * @return The dynamicColumns.
   */
  @java.lang.Override
  public boolean getDynamicColumns() {
    return dynamicColumns_;
  }
  /**
   * <code>bool dynamicColumns = 2;</code>
   * @param value The dynamicColumns to set.
   */
  private void setDynamicColumns(boolean value) {
    
    dynamicColumns_ = value;
  }
  /**
   * <code>bool dynamicColumns = 2;</code>
   */
  private void clearDynamicColumns() {
    
    dynamicColumns_ = false;
  }

  public static tech.donau.behaiv.proto.PredictionSet parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static tech.donau.behaiv.proto.PredictionSet parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static tech.donau.behaiv.proto.PredictionSet parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static tech.donau.behaiv.proto.PredictionSet parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static tech.donau.behaiv.proto.PredictionSet parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static tech.donau.behaiv.proto.PredictionSet parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static tech.donau.behaiv.proto.PredictionSet parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static tech.donau.behaiv.proto.PredictionSet parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static tech.donau.behaiv.proto.PredictionSet parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static tech.donau.behaiv.proto.PredictionSet parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static tech.donau.behaiv.proto.PredictionSet parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static tech.donau.behaiv.proto.PredictionSet parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(tech.donau.behaiv.proto.PredictionSet prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code PredictionSet}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        tech.donau.behaiv.proto.PredictionSet, Builder> implements
      // @@protoc_insertion_point(builder_implements:PredictionSet)
      tech.donau.behaiv.proto.PredictionSetOrBuilder {
    // Construct using tech.donau.behaiv.proto.PredictionSet.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .Prediction prediction = 1;</code>
     */
    @java.lang.Override
    public java.util.List<tech.donau.behaiv.proto.Prediction> getPredictionList() {
      return java.util.Collections.unmodifiableList(
          instance.getPredictionList());
    }
    /**
     * <code>repeated .Prediction prediction = 1;</code>
     */
    @java.lang.Override
    public int getPredictionCount() {
      return instance.getPredictionCount();
    }/**
     * <code>repeated .Prediction prediction = 1;</code>
     */
    @java.lang.Override
    public tech.donau.behaiv.proto.Prediction getPrediction(int index) {
      return instance.getPrediction(index);
    }
    /**
     * <code>repeated .Prediction prediction = 1;</code>
     */
    public Builder setPrediction(
        int index, tech.donau.behaiv.proto.Prediction value) {
      copyOnWrite();
      instance.setPrediction(index, value);
      return this;
    }
    /**
     * <code>repeated .Prediction prediction = 1;</code>
     */
    public Builder setPrediction(
        int index, tech.donau.behaiv.proto.Prediction.Builder builderForValue) {
      copyOnWrite();
      instance.setPrediction(index, builderForValue);
      return this;
    }
    /**
     * <code>repeated .Prediction prediction = 1;</code>
     */
    public Builder addPrediction(tech.donau.behaiv.proto.Prediction value) {
      copyOnWrite();
      instance.addPrediction(value);
      return this;
    }
    /**
     * <code>repeated .Prediction prediction = 1;</code>
     */
    public Builder addPrediction(
        int index, tech.donau.behaiv.proto.Prediction value) {
      copyOnWrite();
      instance.addPrediction(index, value);
      return this;
    }
    /**
     * <code>repeated .Prediction prediction = 1;</code>
     */
    public Builder addPrediction(
        tech.donau.behaiv.proto.Prediction.Builder builderForValue) {
      copyOnWrite();
      instance.addPrediction(builderForValue);
      return this;
    }
    /**
     * <code>repeated .Prediction prediction = 1;</code>
     */
    public Builder addPrediction(
        int index, tech.donau.behaiv.proto.Prediction.Builder builderForValue) {
      copyOnWrite();
      instance.addPrediction(index, builderForValue);
      return this;
    }
    /**
     * <code>repeated .Prediction prediction = 1;</code>
     */
    public Builder addAllPrediction(
        java.lang.Iterable<? extends tech.donau.behaiv.proto.Prediction> values) {
      copyOnWrite();
      instance.addAllPrediction(values);
      return this;
    }
    /**
     * <code>repeated .Prediction prediction = 1;</code>
     */
    public Builder clearPrediction() {
      copyOnWrite();
      instance.clearPrediction();
      return this;
    }
    /**
     * <code>repeated .Prediction prediction = 1;</code>
     */
    public Builder removePrediction(int index) {
      copyOnWrite();
      instance.removePrediction(index);
      return this;
    }

    /**
     * <code>bool dynamicColumns = 2;</code>
     * @return The dynamicColumns.
     */
    @java.lang.Override
    public boolean getDynamicColumns() {
      return instance.getDynamicColumns();
    }
    /**
     * <code>bool dynamicColumns = 2;</code>
     * @param value The dynamicColumns to set.
     * @return This builder for chaining.
     */
    public Builder setDynamicColumns(boolean value) {
      copyOnWrite();
      instance.setDynamicColumns(value);
      return this;
    }
    /**
     * <code>bool dynamicColumns = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDynamicColumns() {
      copyOnWrite();
      instance.clearDynamicColumns();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:PredictionSet)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new tech.donau.behaiv.proto.PredictionSet();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "prediction_",
            tech.donau.behaiv.proto.Prediction.class,
            "dynamicColumns_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0001\u0000\u0001\u001b\u0002\u0007" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<tech.donau.behaiv.proto.PredictionSet> parser = PARSER;
        if (parser == null) {
          synchronized (tech.donau.behaiv.proto.PredictionSet.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<tech.donau.behaiv.proto.PredictionSet>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:PredictionSet)
  private static final tech.donau.behaiv.proto.PredictionSet DEFAULT_INSTANCE;
  static {
    PredictionSet defaultInstance = new PredictionSet();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      PredictionSet.class, defaultInstance);
  }

  public static tech.donau.behaiv.proto.PredictionSet getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PredictionSet> PARSER;

  public static com.google.protobuf.Parser<PredictionSet> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

